package com.bees.brewery.core;

public enum Status {
    FAILED,
    IN_PROGRESS_MALTEACAO,
    IN_PROGRESS_BRASSAGEM,
    IN_PROGRESS_FILTRAGEM,
    IN_PROGRESS_FERVURA,
    FINISHED_MALTEACAO,
    FINISHED_BRASSAGEM,
    FINISHED_FILTRAGEM,
    FINISHED_FERVURA
}
