package com.bees.brewery.core;

public enum Status {
    FAILED,
    IN_PROGRESS_MALTEACAO,
    IN_PROGRESS_BRASSAGEM,
    IN_PROGRESS_FILTRAGEM,
    FINISHED_MALTEACAO,
    FINISHED_BRASSAGEM,
    FINISHED_FILTRAGEM
}
